### PR TITLE
Add contextual functional.

### PR DESCRIPTION
**Pull request by mj4444ru**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | 

I suggest adding the ability to receive objects with a binding to the name in **injector**.

Usage example:

```php
class SiteController
{
    ...
    public function index(TestInterface $test, TestInterface $testA, TestInterface $testB): ResponseInterface
    ...
    public function action1(ConnectionInterface $db): ResponseInterface
    ...
    public function action2(ConnectionInterface $dbA): ResponseInterface
    ...
    public function action3(ConnectionInterface $dbB): ResponseInterface
    ...
    public function action4(ConnectionInterface $dbA, ConnectionInterface $dbB): ResponseInterface
    ...
}
```

DI configuration example (config/common):

```php
return [
    TestInterface::class => TestA::class,
    TestInterface::class . '$testA' => TestA::class,
    TestInterface::class . '$testB' => TestB::class,

    ConnectionInterface::class => function() {
        return new Connection(['dbName'=>'Def']);
    },
    ConnectionInterface::class . '$dbA' => function() {
        return new Connection(['dbName'=>'dbA']);
    },
    ConnectionInterface::class . '$dbB' => function() {
        return new Connection(['dbName'=>'dbB']);
    },
];
```

### CODE REVIEW

**Comment by samdark** [comment]
That likely won't work for a situation with same-named parameters of two different classes.

**Comment by xepozz** [comment]
> That likely won't work for a situation with same-named parameters of two different classes.

What do you mean?

**Comment by samdark** [comment]
Also it will make it impossible to use injector with PSR container. Will require specific implementation.

**Comment by samdark** [comment]
Likely the situation could be solved with explicit controller config in container.

**Comment by roxblnfk** [comment]
@mj4444ru You could use this approach
```php
$injector->invoke($action, [
    'db' => new Connection(['dbName'=>'Def']),
    'dbA' => new Connection(['dbName'=>'dbA']),
    'dbB' => new Connection(['dbName'=>'dbB']),
]);
```
However, there is a problem in making the initialization of parameters deferred (when needed).

I already thought about this functionality, but did not suggest it, so as not to overcomplicate Injector
It might look like this:

```php
$injector->invoke($action, [
    'db' => new Injector\Deferred(fn () => new Connection(['dbName'=>'Def'])),
    'dbA' => new Injector\Deferred(fn () => new Connection(['dbName'=>'dbA'])),
    'dbB' => new Injector\Deferred(fn () => new Connection(['dbName'=>'dbB'])),
    'someValue' => new Injector\Deferred(fn (ContainerInterface $container) => $container->get('someValue')),
]);
```

**Comment by mj4444ru** [comment]
> @mj4444ru You could use this approach
> 
> ```
> $injector->invoke($action, [
>     'db' => new Connection(['dbName'=>'Def']),
>     'dbA' => new Connection(['dbName'=>'dbA']),
>     'dbB' => new Connection(['dbName'=>'dbB']),
> ]);
> ```
> 
> However, there is a problem in making the initialization of parameters deferred (when needed).
> 
> I already thought about this functionality, but did not suggest it, so as not to overcomplicate Injector
> It might look like this:
> 
> ```
> $injector->invoke($action, [
>     'db' => new Injector\Deferred(fn () => new Connection(['dbName'=>'Def'])),
>     'dbA' => new Injector\Deferred(fn () => new Connection(['dbName'=>'dbA'])),
>     'dbB' => new Injector\Deferred(fn () => new Connection(['dbName'=>'dbB'])),
>     'someValue' => new Injector\Deferred(fn (ContainerInterface $container) => $container->get('someValue')),
> ]);
> ```

Why would the calling code know anything about the action?

**Comment by roxblnfk** [comment]
> Why would the calling code know anything about the action?

At least this code knows what it runs.


The purpose of your proposal is clear, but it cannot be realized in this form.
In your proposal, the injector dictates the format for storing IDs in the container. This is not desirable.

**Comment by mj4444ru** [comment]
> > Why would the calling code know anything about the action?
> 
> At least this code knows what it runs.
> 
> The purpose of your proposal is clear, but it cannot be realized in this form.
> In your proposal, the injector dictates the format for storing IDs in the container. This is not desirable.

What if he doesn't know?

Why exactly it cannot be implemented in such a form?

In my proposal, DI is just a repository that does not know what is stored in it.
It is undesirable for a simple user to work with a container and an injector.

**Comment by mj4444ru** [comment]
> Also it will make it impossible to use injector with PSR container. Will require specific implementation.

What is the assertion based on?

**Comment by xepozz** [comment]
@samdark Isn't `$container->get('my-service')` an PSR-compatible call?

**Comment by samdark** [comment]
<strike>@xepozz, @mj4444ru currently the calls are:

```php
$container->get(Connection::class);
```

new calls will be:

```php
$container->get(Connection::class . '$methodName');
```

It is, indeed, PSR-compatible but in order for it to work container must be aware of special `$method` syntax.</strike>

**Comment by samdark** [comment]
OK, I was wrong and it's fully compatible with previous container. In the "context" mode it will double the number of calls though but that's usually a single `isset` so should not matter that much.

**Comment by roxblnfk** [comment]
> Why exactly it cannot be implemented in such a form?

@mj4444ru I suggest another draft that looks more flexible -- #32
It seems to me that it completely covers your case. What do you think about it?

**Comment by samdark** [comment]
Closing this one since @roxblnfk, indeed covers the case. @mj4444ru thanks for interesting idea.

**Pull request closed without merging**
